# -*- coding: utf-8 -*-
{
    'name': 'Invoice Customer Remake',
    'version': '13.0.1.0',
    'category': '',
    'description': u"""
This module has been generated by Odoo Studio.
It contains the apps created with Studio and the customizations of existing apps.
""",
    'author': 'minhgroup',
    'depends': [
        'account', 'Maintain_Client', 'Maintain_Organization'

    ],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/sequence.xml',
        'views/add_js.xml',
        'views/account_payment_custom_view.xml',
#        'views/invoice_customer_custom_view.xml',
        'views/report_invoice.xml',
        'report/report_format1.xml',
        'report/report_format2.xml',
        'report/report_format3.xml',
        'report/report_format4.xml',
        'report/report_shipment1.xml'
    ],
    'qweb': [
        'static/src/xml/report_template.xml'
    ],
    'application': False,
    'license': 'OPL-1',
}
